import type { NextPage } from "next";
import Head from "next/head";
import About from "../components/aboutme/about";
import Footer from "../components/footer/footer";
import Header from "../components/header/header";
import Hero from "../components/hero/hero";
import Skills from "../components/skills/skills";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Hamza Rafique</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="rounded-lg h-auto bg-hero-background flex flex-col">
        <Header />
        <Hero />
      </div>
      <About />
      <Skills />
      <Footer />
    </>
  );
};

export default Home;
