import type { NextPage } from "next";
import Head from "next/head";
import About from "../components/aboutme/about";
import Footer from "../components/footer/footer";
import Header from "../components/header/header";
import Hero from "../components/hero/hero";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Hamza Rafique</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="rounded-lg h-auto bg-hero-background flex flex-col">
        <Header />
        <Hero />
      </div>
      <About />

      <main className={styles.main}>
        <h1 className="text-3xl font-bold underline">Hello world!</h1>
      </main>
      <Footer />
    </>
  );
};

export default Home;
